### ISSUE TITLE
Single quotes are breaking HTML attribute in 1.0.14

### ISSUE THREAD

**Issue by CodelineRed** [nfplee/gulp-vue-single-file-component#5]
[My file and row](https://github.com/InsanityMeetsHH/vue-skeleton/blob/master/src/js/vue/component/page/home.vue#L35)

My Vue code:
`data-slick='{"responsive": [{"breakpoint": 575,"settings": {"slidesToShow": 2 ...`

Transpiled with 1.0.12 (working)
`data-slick="{&quot;responsive&quot;: [{&quot;breakpoint&quot;: 575,&quot;settings&quot;: {&quot;slidesToShow&quot;: 2 ...`

Transpiled with 1.0.14 (not working)
`data-slick=&#39;{"responsive": [{"breakpoint": 575,"settings": {"slidesToShow": 2 ...`

My Vue code work around for 1.0.14:
`data-slick="{&quot;responsive&quot;: [{&quot;breakpoint&quot;: 575,&quot;settings&quot;: {&quot;slidesToShow&quot;: 2 ...`

**Comment by nfplee** [comment]
This should be fixed in 1.0.15. Please let me know if there's any problems.

**Comment by CodelineRed** [comment]
Hello @nfplee 

Your fix in 1.0.15 solves the problem.

Thank you 😊
