### ISSUE TITLE
Splitted html tags are missing a white space after minify

### ISSUE THREAD

**Issue by macjohn2** [nfplee/gulp-vue-single-file-component#6]
<a
  href=#"
  id="foo">bar</a>
result is <ahref="#"id="foo">bar</a>

instead of:
function minify(input) {
    return input.split('\n').map(function(line) {
        return line.trim();
    }).filter(function(line) {
        return line != '';
    }).join('');
}

perhaps something like:

function minify(input) {
    return input.split('\n').map(function(line) {
        return line.slice(-1) === '>' ? line.trim() : line.trim() + ' ';
    }).filter(function(line) {
        return line != '';
    }).join('');
}

if line is not closing with end tag '>', add a space after trimming

**Comment by nfplee** [comment]
I've removed the call to minify the code and instead simply trimmed it to remove the whitespace at the start and the end. Please let me know if there's any problems. Thanks
