### ISSUE TITLE
Template Literals are Escaped

### ISSUE THREAD

**Issue by justwiebe** [nfplee/gulp-vue-single-file-component#7]
```html
<template>
  <button
    :id="`my-dynamic-id-${id}`"
  >
    Text
  </button>
</template>
```
Is converted to 
```html
template: "<button\n      :id=\"&#96;my-dynamic-id-".concat(id, "&#96;\"\n    >\n      Text\n    </button>"
```
I'm pretty sure that `.concat` is coming from gulp-babel, but `&#96;` is coming from this

**Comment by nfplee** [comment]
Could you not replace it with the following instead of using a template literal?:

```html
<template>
  <button
    :id="'my-dynamic-id' + id"
  >
    Text
  </button>
</template>
```

I'm open for suggestions if you have a better solution.

**Comment by justwiebe** [comment]
@nfplee That's what I'm doing as a workaround, but my company's style guide forbids that, also it gets a little bit more ugly as things get complicated `:style="{'flex': '1 1 ' + sliderWidth + '%'}"`. Another workaround is to put it in a computed, but this is liable to cause issues when somebody else in our company adds to this repo not understanding that template literals are a problem

Is there a reason why template literals have to be escaped?

**Comment by nfplee** [comment]
This should now be fixed. Please reopen and let me know any problems if it's still causing an issue. Thanks
